import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import Footer from "./ui/footer";
import MobileHeader from "./ui/mobileHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gonano",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-lvw">
      <body
      
        className={`${montserrat.variable} antialiased h-full w-full`}
      >
        <Header/>
        <MobileHeader />
        <div className="">
          {children}
        </div>
        <footer className="w-lvw min-h-1/2 absolute">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
